### ISSUE TITLE
Does Intercom.js require Node.js or Socket.io

### ISSUE THREAD

**Issue by iamdriz** [diy/intercom.js#12]
From the introduction it says that intercom.js includes a binding for socket.io, but doesn't elaborate if it's a requirement for it to work... or if node.js is required.

Also what is the main difference between socket.io and intercom.js?

Thanks

**Comment by InstanceOfMichael** [comment]
I use Intercom.js without the sockets at all, it works pretty good. As a plus, I'm planning on adding sockets to my project soon.
